"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [count, setCount] = useState(0);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ border: "2px solid red", padding: "20px" }}>
          <button onClick={() => setCount((cur) => cur + 1)}>업</button>
          <br />
          <button onClick={() => setCount((cur) => cur - 1)}>다운</button>
          <br />

          <b>변경된 카운터는 : {count}</b>
          <br />
          <p>여기까지가 레이아웃이에요! 카운터는 유지될까요?</p>
          <p>유지가 되네요! 레이아웃 리렌더링은 정말 일어나지 않는군요.</p>
          <div style={{ border: "1px solid white", padding: "10px" }}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
